# Generated by Django 5.1.5 on 2025-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='mail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
