# Generated by Django 5.1.5 on 2025-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_alter_usuariopersonalizado_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='mail',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
